Update Lagom to 1.2.0
Also revert back to Play 2.5.4

This is because Lagom 1.2.0 depends on Play 2.5.4 which has dependency on Async HTTP Client 2.0.2.

https://github.com/lagom/lagom/blob/1.2.0/build.sbt#L16

Moving to latest Play (2.5.10 at the time of the commit) will bring in AHC 2.0.11 that drops CleanupChannelGroup which is a public API, causing NoClassDefFoundError when used with Lagom.

https://github.com/AsyncHttpClient/async-http-client/commit/03ac5e18006b6c48984a7ca1d4b159b6b20cc44a